preload = /home/yv/Pictures/Wallpapers/ObjetivoFinal.png
preload = /home/yv/Pictures/Wallpapers/jolentadraka.png

wallpaper {
  monitor = DP-1
  path = /home/yv/Pictures/Wallpapers/ObjetivoFinal.png
}

wallpaper {
  monitor = DP-2
  path = /home/yv/Pictures/Wallpapers/jolentadraka.png
}

splash = false
