[colors]
indexed_colors = []

[colors.bright]
black = "0x4d4d4d"
blue = "0xcaa9fa"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff92d0"
red = "0xff6e67"
white = "0xe6e6e6"
yellow = "0xf4f99d"

[colors.cursor]
cursor = "0xf8f8f2"
text = "0x44475a"

[colors.dim]
black = "0x14151b"
blue = "0x4d5b86"
cyan = "0x59dffc"
green = "0x1ef956"
magenta = "0xff46b0"
red = "0xff2222"
white = "0xe6e6d1"
yellow = "0xebf85b"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbfbfbf"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x282a36"
foreground = "0xf8f8f2"

[colors.selection]
background = "0x44475a"
text = "0xf8f8f2"

[font]
size = 11.0

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "K"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "J"
mods = "Control|Alt"

[window]
startup_mode = "Windowed"
opacity = 0.96


[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2

[scrolling]
history = 10000
